"""empty message

Revision ID: 3576c6a26cb2
Revises: cb996f04ecab
Create Date: 2023-05-01 15:05:01.421892

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3576c6a26cb2'
down_revision = 'cb996f04ecab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('time', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('threads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('threads_name', sa.String(length=200), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('section', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('under_threads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('threads_name', sa.String(), nullable=True),
    sa.Column('threads_text', sa.String(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('time', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('under_threads')
    op.drop_table('threads')
    op.drop_table('messages')
    # ### end Alembic commands ###
