"""empty message

Revision ID: ab08bd8686ed
Revises: 
Create Date: 2023-04-25 20:07:29.153350

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab08bd8686ed'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=500), nullable=True),
    sa.Column('get_email_from_group', sa.Boolean(), nullable=True),
    sa.Column('get_ping_from_group', sa.Boolean(), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('show_date_of_birth', sa.Boolean(), nullable=True),
    sa.Column('adress', sa.String(length=300), nullable=True),
    sa.Column('sex', sa.String(length=10), nullable=True),
    sa.Column('about_me', sa.Text(length=400), nullable=True),
    sa.Column('avatar', sa.BLOB(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)

    op.create_table('threads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('threads_name', sa.String(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('section', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['section'], ['sections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('under_threads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('threads_name', sa.String(), nullable=True),
    sa.Column('threads_text', sa.String(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('time', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['threads.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('time', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['under_threads.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('messages')
    op.drop_table('under_threads')
    op.drop_table('threads')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    # ### end Alembic commands ###
