"""empty message

Revision ID: c1f88f3f7a21
Revises: def7fb740a77
Create Date: 2023-05-01 15:37:59.983680

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c1f88f3f7a21'
down_revision = 'def7fb740a77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('under_threads', schema=None) as batch_op:
        batch_op.alter_column('threads_text',
               existing_type=mysql.VARCHAR(length=400),
               type_=sa.String(length=1500),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('under_threads', schema=None) as batch_op:
        batch_op.alter_column('threads_text',
               existing_type=sa.String(length=1500),
               type_=mysql.VARCHAR(length=400),
               existing_nullable=True)

    # ### end Alembic commands ###
