"""empty message

Revision ID: def7fb740a77
Revises: 3576c6a26cb2
Create Date: 2023-05-01 15:05:38.947474

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'def7fb740a77'
down_revision = '3576c6a26cb2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('under_threads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('threads_name', sa.String(length=400), nullable=True),
    sa.Column('threads_text', sa.String(length=400), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('time', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('under_threads')
    # ### end Alembic commands ###
